---
title: "TP_markdown_correction_honey_production"
author: "Aynaz"
date: "`r Sys.Date()`"
output: html_document
---

### Data Preparation

```{r}
# 1. Install missing packages ----
list.of.packages <- c("lubridate","cowplot","scales","DataCombine","stargazer","sandwich","dyn","lmtest","data.table","tidyr","readr","stringr","forecast","gridExtra","usmap","ggthemes","shinythemes","rsconnect","fiftystater","agridat")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
```

```{r}
#Install/load pacman
if(!require(pacman)){install.packages("pacman");require(pacman)}
#Install/load tons of packages
p_load(lubridate,cowplot,scales,DataCombine,stargazer,sandwich,dyn,lmtest,data.table,tidyr,readr,stringr,forecast,gridExtra,usmap,ggthemes,shinythemes,rsconnect)
```

```{r}
#install.packages('tidyverse')
library(tidyverse)
```

```{r}
#Load Data
getwd()
#setwd("G://Utilisateurs//aynaz.adlzarrabi//Documents//archive")
honeyfinaldf <- read.csv("honeyproduction.csv", sep=",")
honeyfinaldf <- data.frame(honeyfinaldf)
honeyfinaldf
```

```{r}
honeyfinaldf$consumption <- honeyfinaldf$totalprod-honeyfinaldf$stocks
#or 
str(honeyfinaldf)
```

### Honey Production Yield Change From 1998 to 2012

#### missing value counter

```{r}
colSums(is.na(honeyfinaldf))
```

#### number of states by years

```{r}
table(honeyfinaldf$year)
```

```{r}
summary_stats <- summary(honeyfinaldf$yieldpercol)
mean_yield <- mean(honeyfinaldf$yieldpercol, na.rm = TRUE)
sd_yield <- sd(honeyfinaldf$yieldpercol, na.rm = TRUE)
summary_stats
mean_yield
sd_yield
```

```{r}
reviews_per_state <- table(honeyfinaldf$state)
reviews_per_state
```

```{r}
change <- honeyfinaldf %>%
  group_by(year) %>%
  summarise(YearTotal=sum(totalprod))
change
```

```{r}
average_price_per_state <- aggregate(honeyfinaldf$priceperlb, by=list(honeyfinaldf$state), FUN=mean, na.rm = TRUE)
average_price_per_state
```

```{r}
average_yield_by_state <- honeyfinaldf %>%
  group_by(state) %>%
  summarise(average_yield = mean(yieldpercol, na.rm = TRUE)) %>%
  arrange(desc(average_yield))
average_yield_by_state
```

```{r}
ggplot(honeyfinaldf, aes(x = state, y = yieldpercol)) +
  geom_bar(stat = "identity", fill = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Production moyenne de miel par État", x = "État", y = "Production (lbs)")
```

```{r}
# Faceted line plot for 'yieldpercol' over 'year' by 'state'
ggplot(honeyfinaldf, aes(x = year, y = yieldpercol, group = state, color = factor(state))) +
  geom_line() +
  facet_wrap(~state) +
  theme(legend.position = "none") +
  labs(title = "Honey Yield per Colony over Years by State", x = "Year", y = "Yield per Colony")
```

```{r}
ggplot(data=change, aes(x=year, y=YearTotal/1000000)) + 
  geom_smooth(method = "lm") + 
  geom_line(color = "red", size = 2) +
  geom_point() +
  scale_x_continuous(breaks=seq(1998, 2012, 2)) +
  ylab("Production (in Million lb)") +
  xlab("Years") +
  background_grid(major = "xy", minor="y", size.major = 0.2) 
```

### Which state produce the most honey? Which produces the least?

```{r}
productionperstate <- honeyfinaldf %>%
    group_by(state) %>%
    summarise(sumprod=sum(totalprod)) %>%
    arrange(desc(sumprod)) %>%
    head(10) %>%
    mutate(percentage=round(sumprod/sum(sumprod)*100,2))
productionperstate
```

```{r}
ggplot(data=productionperstate, aes(x=reorder(state,sumprod),y=sumprod/1000000))+
    geom_col(aes(fill=state),show.legend=F)+
    geom_text(aes(label=percentage))+
    coord_flip()+
    labs(x="States in the USA",y="Total Honey Produced (in Million lb)",title="Total Honey Produced by Each State") 
```

```{r}
productnperstate <- honeyfinaldf %>%
    group_by(state) %>%
    summarise(sumprod=sum(totalprod)) %>%
    arrange(sumprod) %>%
    head(10) %>%
    mutate(percentage=round(sumprod/sum(sumprod)*100,2))
productnperstate
```

```{r}
ggplot(data=productnperstate, aes(x=reorder(state,sumprod),y=sumprod/1000000))+
    geom_col(aes(fill=state),show.legend=F)+
    geom_text(aes(label=percentage))+
    coord_flip()+
    labs(x="States in the USA",y="Total Honey Produced (in Million lb)",title="Total Honey Produced by Each State") 
```

```{r}
# Top 10 states producing most honey in 1998
productionnper1998 <- honeyfinaldf %>%
    filter(year==1998) %>%
    group_by(state) %>%
    summarise(sumprod=sum(totalprod)) %>%
    arrange(desc(sumprod)) %>%
    head(10) %>%
    mutate(percentage=round(sumprod/sum(sumprod)*100,2))
productionnper1998
```

```{r}
y1998 <- ggplot(data = productionnper1998, aes(x=reorder(state,sumprod),y=sumprod/1000000, fill = state)) +
  geom_bar(stat = "identity") +
  guides() + 
  xlab("State") + 
  ylab("Total Honey Produced (in Million lb)") +
  ggtitle("Honey Production in 1998") +
  coord_flip()
y1998
```

```{r}
library(ggplot2)
library(shiny)
library(dplyr)

# Load the data
# Remplacez cela par le chargement de votre propre ensemble de données si nécessaire


library(shiny)
library(ggplot2)
library(dplyr)

# UI
ui <- fluidPage(
  titlePanel("Boxplot des prix du miel par État"),
  sidebarLayout(
    sidebarPanel(
      helpText("Sélectionnez un état pour voir la distribution des prix du miel."),
      selectInput("selected_state", "Choisir un état:", choices = NULL) # Les choix sont définis dans server.R
    ),
    mainPanel(
      plotOutput("priceBoxplot")
    )
  )
)

# Server logic
server <- function(input, output, session) {
  
  # Assume honey_data is already loaded
  # Remplacez le chemin par le chemin réel de votre fichier CSV
  honey_data <- read.csv('honeyproduction.csv', stringsAsFactors = FALSE)
  
  # Mettre à jour les choix de selectInput en fonction des états disponibles
  observe({
    updateSelectInput(session, "selected_state", choices = unique(honey_data$state))
  })
  
  # Render boxplot pour les prix du miel basés sur l'état sélectionné
  output$priceBoxplot <- renderPlot({
    # Filtrer les données pour l'état sélectionné
    state_data <- honey_data %>% filter(state == input$selected_state)
    
    # Créer le boxplot
    ggplot(state_data, aes(x = factor(state), y = priceperlb)) +
      geom_boxplot() +
      labs(title = paste("Distribution des prix du miel pour l'état:", input$selected_state),
           x = "État", y = "Prix par livre")
  })
}

# Run the application
shinyApp(ui = ui, server = server)

```

```{r}
# Top 10 states producing most honey in 2012
productionnper2012 <- honeyfinaldf %>%
    filter(year==2012) %>%
    group_by(state) %>%
    summarise(sumprod=sum(totalprod)) %>%
    arrange(desc(sumprod)) %>%
    head(10) %>%
    mutate(percentage=round(sumprod/sum(sumprod)*100,2))
productionnper2012
```

```{r}
y2012 <- ggplot(data = productionnper2012, aes(x=reorder(state,sumprod),y=sumprod/1000000, fill = state)) +
  geom_bar(stat = "identity") +
  guides(fill = FALSE) + 
  xlab("State") + 
  ylab("Total Honey Produced (in Million lb)") +
  ggtitle("Honey Production in 2012") +
  coord_flip()
grid.arrange(y1998, y2012, ncol=2)
```

### Trends

```{r}
change <- honeyfinaldf %>%
  group_by(year) %>%
  summarise(YearTotal=sum(totalprod))
change
```

```{r}
ggplot(data=change, aes(x=year, y=YearTotal/1000000)) + 
  geom_smooth(method = "lm") + 
  geom_line(color = "red", size = 2) +
  geom_point() +
  scale_x_continuous(breaks=seq(1998, 2012, 2)) +
  ylab("Production (in Million lb)") +
  xlab("Years") +
  background_grid(major = "xy", minor="y", size.major = 0.2) 
```

```{r}
price <- honeyfinaldf %>%
  group_by(year) %>%
  summarise(YearAvgPrice=mean(priceperlb))
price
```

```{r}
ggplot(data=price, aes(x=year, y=YearAvgPrice)) + 
  geom_smooth(method = "lm") + 
  geom_line(color = "red", size = 2) +
  geom_point() +
  scale_x_continuous(breaks=seq(1998, 2012, 2)) +
  ylab("Prices (Avg)") +
  xlab("Years") +
  background_grid(major = "xy", minor="y", size.major = 0.2) 
```

```{r}
ProductionPerYear <- honeyfinaldf %>%
    group_by(year) %>%
    summarize(TotalConsumption=sum(consumption))
ProductionPerYear
```

```{r}
ggplot(ProductionPerYear,aes(x=year,y=TotalConsumption/1000000)) +
    geom_smooth(method = "lm") + 
    geom_line(color="red", size=2) +
    geom_point() +
    scale_x_continuous(breaks=seq(1998, 2012, 2)) +
    labs(x="Year", y="Total Consumption (in Million lb)", title="Total Consumption for years(1998-2012)") +
    background_grid(major = "xy", minor="y", size.major = 0.2)

```

```{r}
hny <- honeyfinaldf %>% 
    group_by(year) %>% 
    summarise(totalproduction=sum(totalprod), VoP=sum(prodvalue)) 
hny
```

```{r}
ggplot(hny) +
    geom_smooth(aes(x=year,y=totalproduction/1000000), method = "lm", color="blue", size=1, se=FALSE) + 
    geom_smooth(aes(x=year,y=VoP/1000000), method = "lm", color="darkblue", size=1, se=FALSE) + 
    geom_line(aes(x=year,y=totalproduction/1000000), color="red", size=2) +
    geom_line(aes(x=year,y=VoP/1000000), color="green", size=2) +
    geom_point(aes(x=year,y=totalproduction/1000000)) +
    geom_point(aes(x=year,y=VoP/1000000)) +
    scale_x_continuous(breaks=seq(1998, 2012, 2)) +
    labs(x="Year", y="", title="Total Honey Production Vs. Value of Production") +
    background_grid(major = "xy", minor="y", size.major = 0.2)
```

### Time series Model

```{r}
honey <- honeyfinaldf %>%
  group_by(year) %>%
  summarise(total_prod=sum(totalprod))
honey_production <- ts(honey$total_prod, start=1998, frequency=1)
honey
plot(honey_production/1000000, ylab="Honey Production (in Million lb)")
```

```{r}
ets2013 <- forecast(honey_production, h=1)
plot(ets2013,  ylab="Honey Production")
```

```{r}
naive2013 <- forecast(naive(honey_production, h=1))
plot(naive2013, ylab="Honey Production")
```

```{r}
ses2013 <- forecast(ses(honey_production, h = 1))
plot(ses2013, ylab="Honey Production")
```

```{r}
arima2013 <- forecast(auto.arima(honey_production), h=1)
tbats2013 <- forecast(tbats(honey_production), h=1)
nnetar2013 <- forecast(nnetar(honey_production), h=1)
```

```{r}
rbindlist(list(
  data.table(method = 'naive', as.data.frame(accuracy(naive2013))),
  data.table(method = 'ses', as.data.frame(accuracy(ses2013))),
  data.table(method = 'ets', as.data.frame(accuracy(ets2013))),
  data.table(method = 'arima', as.data.frame(accuracy(arima2013))),
  data.table(method = 'tbats', as.data.frame(accuracy(tbats2013))),
  data.table(method = 'nnetar', as.data.frame(accuracy(nnetar2013)))))
```

```{r}
library(shiny)  
library(ggplot2) 
library(dplyr)
library(agridat)
install.packages("DT", type = "binary")
library(DT)

```

```{r}
#load_data
honey<- as.data.frame(honeyfinaldf)
honey_histogram<-honeyfinaldf %>%
  filter(year==2012) %>%
    group_by(state) %>%
    summarise(sumprod=sum(totalprod)/1000000,sumconsum=sum(consumption)/1000000,YearAvgPrice=mean(priceperlb))
honey_histogram
```

```{r}
honey_ts<-honeyfinaldf %>%
    group_by(year) %>%
    summarise(sumprod=sum(totalprod)/1000000,sumconsum=sum(consumption)/1000000,YearAvgPrice=mean(priceperlb))
honey_ts
```

```{r}
honey_hist_tab <- tabPanel(
  "honey_histogram",
  selectInput("honey_hist_dv", "DV", choices = names(honey_histogram)[2:4]),
  plotOutput("honey_hist_plot"),
  DT::dataTableOutput("honey_hist_table")
)

honey_ts_tab <- tabPanel(
  "honey_histogram",
  selectInput("honey_ts_dv", "DV", choices = names(honey_ts)[2:4]),
  plotOutput("honey_ts_plot"),
  DT::dataTableOutput("honey_ts_table")
)
```

```{r}
tabPanelUI <- function(id, choices) {
    ns <- NS(id)
    
    tabPanel(
        id,
        selectInput(ns("dv"), "DV", choices = choices),
        plotOutput(ns("plot")),
        DT::dataTableOutput(ns("table"))
    )
}
```

```{r}
honey_hist_tab <- tabPanelUI("honey_histogram", names(honey_histogram)[2:4])
honey_ts_tab <- tabPanelUI("honey_ts", names(honey_ts)[2:4])
```

#changer le year en date

```{r}
honey_ts=as.Date(honey_ts$year)
```

```{r}
# libraries ----
#install.packages("shinyjs")
library(shinyjs)
library(shiny)
library(shinydashboard)
library(ggplot2)
library(DT)


# setup ----
theme_set(theme_minimal(base_size = 16)) # ggplot theme

# functions ----
#source("scripts/func.R") # helper functions

# modules ----
tabPanelUI <- function(id, choices) { 
    ns <- NS(id)
    
    tabPanel(
        id,
        selectInput(ns("dv"), "DV", choices = choices),
        plotOutput(ns("plot")),
        DT::dataTableOutput(ns("table"))
    )
}

tabPanelServer <- function(id, data, group_by) { 
    moduleServer(id, function(input, output, session) {
        output$table <- DT::renderDataTable({
            data
        })
        
        output$plot <- renderPlot({
            # handle non-string groupings
            data[[group_by]] <- factor(data[[group_by]])
            ggplot(data, aes(x = .data[[group_by]], 
                             y = .data[[input$dv]],
                             fill = .data[[group_by]])) +
                #geom_bar(stat = "identity") +
                #guides()
                geom_smooth(method = "lm") + 
                geom_line(color="red", size=2) +
                geom_point() +
                #scale_x_continuous(breaks=seq(1998, 2012, 2)) +
                labs(x="Year", y="Total Consumption (in Million lb)", title="Total Consumption for years(1998-2012)") +
                background_grid(major = "xy", minor="y", size.major = 0.2)  
        })
    })
}

# UI ----
honey_hist_tab <- tabPanelUI("honey_histogram", names(honey_histogram)[2:4])
honey_ts_tab <- tabPanelUI("honey_ts", names(honey_ts)[2:4])

ui <- dashboardPage(
    skin = "purple",
    dashboardHeader(title = "Modules Demo"),
    dashboardSidebar(disable = TRUE),
    dashboardBody(
        shinyjs::useShinyjs(),
        tags$head(
            tags$link(rel = "stylesheet", type = "text/css", href = "custom.css")
        ), 
        tabsetPanel(
            honey_hist_tab,
            honey_ts_tab
        )
    )
)

# server ----
server <- function(input, output, session) {
    tabPanelServer("honey_histogram", data = honey_histogram, group_by = "state")
    tabPanelServer("honey_ts", data = honey_ts, group_by = "year")
} 

shinyApp(ui, server)
```
